# This file declares what conda and pip packages are required on the server in order to run properly
# MyBinder.org and other services will by convention install these automatically
channels:
- damianavila82
- conda-forge
- defaults
dependencies:
- jupyterlab=0.32.1
- numpy
- sympy
- matplotlib
- ipywidgets
- ipyvolume
- pip:
  - plotly
  - traitlets
  - ipython
  - pandas
  - vdom
  - jupyterlab_launcher
  - jupyterlab_latex
  - jupyterlab_widgets
